export function generatePythonScript(
  pexelsApiKey: string = "h1r1DWw3EyuEcP8pFXl6e9jo76I0RfxUoG3d18kvEliS6pH6eEyHbmNo",
  pixabayApiKey: string = "35348186-369453ead8e33f2eec3ada4ec",
  outputDir: string = "./kdenlive_media_assets"
): string {
  return `"""
AI Video B-Roll Asset Downloader for Kdenlive / DaVinci / Premiere
Processes a script_plan.json generated by the AI Video B-Roll Assistant
and downloads stock video/photo assets with robust rate-limit and header handling.
"""

import os
import sys
import time
import json
import random

# Use requests if installed; otherwise fall back seamlessly to urllib
try:
    import requests
    USE_REQUESTS = True
except ImportError:
    USE_REQUESTS = False
    import urllib.request
    import urllib.error
    import urllib.parse

# ==========================================
# CONFIGURATION & API KEYS
# ==========================================
PEXELS_API_KEY = os.getenv("PEXELS_API_KEY", "${pexelsApiKey}")
PIXABAY_API_KEY = os.getenv("PIXABAY_API_KEY", "${pixabayApiKey}")

# Standard Desktop User-Agent to prevent Cloudflare/CDN 403 Forbidden blocks
BROWSER_USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"

# Output folder for video editor (e.g. Kdenlive, Premiere, DaVinci)
OUTPUT_DIR = "${outputDir}"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Rate-limit & retry configuration
MAX_RETRIES = 5
INITIAL_BACKOFF = 2.0  # seconds
BACKOFF_FACTOR = 2.0
JITTER_MAX = 1.0


def robust_get_request(url, headers=None, params=None, service_name="API"):
    """
    Performs HTTP GET with exponential backoff, rate-limit (429) handling,
    and realistic browser headers to prevent 403 Forbidden blocks.
    """
    req_headers = {
        "User-Agent": BROWSER_USER_AGENT,
        "Accept": "*/*",
    }
    if headers:
        req_headers.update(headers)

    attempt = 0
    backoff = INITIAL_BACKOFF

    while attempt < MAX_RETRIES:
        attempt += 1
        try:
            if USE_REQUESTS:
                response = requests.get(url, headers=req_headers, params=params, timeout=25)
                status_code = response.status_code
                res_headers = response.headers
            else:
                full_url = url
                if params:
                    query_str = urllib.parse.urlencode(params)
                    full_url = f"{url}?{query_str}"
                req = urllib.request.Request(full_url, headers=req_headers)
                try:
                    res_obj = urllib.request.urlopen(req, timeout=25)
                    status_code = res_obj.status
                    res_headers = dict(res_obj.headers)
                    # Fake requests-like response
                    class FakeResponse:
                        def __init__(self, code, hdrs, data):
                            self.status_code = code
                            self.headers = hdrs
                            self._data = data
                        def json(self):
                            return json.loads(self._data.decode('utf-8'))
                    response = FakeResponse(status_code, res_headers, res_obj.read())
                except urllib.error.HTTPError as e:
                    status_code = e.code
                    res_headers = dict(e.headers)
                    response = None

            # Rate limit exceeded (HTTP 429)
            if status_code == 429:
                retry_after = res_headers.get("Retry-After")
                reset_time = res_headers.get("X-Ratelimit-Reset") or res_headers.get("X-RateLimit-Reset")
                
                wait_time = backoff + random.uniform(0, JITTER_MAX)
                if retry_after and retry_after.isdigit():
                    wait_time = max(float(retry_after), wait_time)
                elif reset_time and reset_time.isdigit():
                    time_until_reset = max(0, int(reset_time) - int(time.time()))
                    if 0 < time_until_reset < 60:
                        wait_time = time_until_reset + 1

                print(f"  [!] Rate limit reached for {service_name} (HTTP 429). Retrying in {wait_time:.1f}s (Attempt {attempt}/{MAX_RETRIES})...")
                time.sleep(wait_time)
                backoff *= BACKOFF_FACTOR
                continue
                
            # Server errors (5xx)
            elif 500 <= status_code < 600:
                wait_time = backoff + random.uniform(0, JITTER_MAX)
                print(f"  [!] {service_name} server error ({status_code}). Backing off {wait_time:.1f}s...")
                time.sleep(wait_time)
                backoff *= BACKOFF_FACTOR
                continue
                
            # Log quota remaining if available
            remaining = res_headers.get("X-Ratelimit-Remaining") or res_headers.get("X-RateLimit-Remaining")
            if remaining is not None:
                try:
                    rem_int = int(remaining)
                    if rem_int <= 5:
                        print(f"  [i] Notice: {service_name} quota low! Only {rem_int} requests remaining in current window.")
                except (ValueError, TypeError):
                    pass

            return response
            
        except Exception as e:
            wait_time = backoff + random.uniform(0, JITTER_MAX)
            print(f"  [!] Network issue ({type(e).__name__}: {e}). Retrying in {wait_time:.1f}s...")
            time.sleep(wait_time)
            backoff *= BACKOFF_FACTOR

    print(f"  [X] Max retries ({MAX_RETRIES}) reached for {service_name}.")
    return None


def verify_mp4_integrity(file_path):
    """
    Verifies that the downloaded file is a genuine MP4 container
    and not an HTML error page or 0-byte corrupt file.
    """
    if not os.path.exists(file_path):
        return False
    size = os.path.getsize(file_path)
    if size < 50000:  # Valid video clips are at least ~50KB
        return False
    try:
        with open(file_path, "rb") as f:
            header = f.read(32)
            # Check for standard MP4 container signature (ftyp) or video streams
            if b"ftyp" in header or b"moov" in header:
                return True
            # Check if it was accidentally an HTML error page
            if b"<!DOCTYPE" in header or b"<html" in header or b"403 Forbidden" in header:
                return False
    except Exception:
        return False
    return True


def download_file_stream(download_url, dest_path, scene_num, provider):
    """
    Downloads large media file with standard browser headers and
    verifies file integrity to prevent 0xc10100be playback errors.
    """
    req_headers = {
        "User-Agent": BROWSER_USER_AGENT,
        "Accept": "*/*",
        "Referer": "https://www.pexels.com/" if provider == "Pexels" else "https://pixabay.com/",
    }

    try:
        if USE_REQUESTS:
            with requests.get(download_url, headers=req_headers, stream=True, timeout=35) as r:
                if r.status_code != 200:
                    print(f"  [X] HTTP {r.status_code} received from {provider} for Scene {scene_num}")
                    return False
                
                content_type = r.headers.get("content-type", "").lower()
                if "text/html" in content_type or "application/json" in content_type:
                    print(f"  [X] Received unexpected content type '{content_type}' (expected video/mp4)")
                    return False

                total_bytes = int(r.headers.get('content-length', 0))
                downloaded = 0
                
                with open(dest_path, 'wb') as f:
                    for chunk in r.iter_content(chunk_size=65536):
                        if chunk:
                            f.write(chunk)
                            downloaded += len(chunk)
        else:
            req = urllib.request.Request(download_url, headers=req_headers)
            with urllib.request.urlopen(req, timeout=35) as resp:
                if resp.status != 200:
                    return False
                content_type = resp.headers.get("content-type", "").lower()
                if "text/html" in content_type:
                    return False
                with open(dest_path, 'wb') as f:
                    while True:
                        chunk = resp.read(65536)
                        if not chunk:
                            break
                        f.write(chunk)

        # Integrity Check
        if verify_mp4_integrity(dest_path):
            size_mb = os.path.getsize(dest_path) / (1024 * 1024)
            print(f"  [✓] Scene {scene_num:02d} verified & saved from {provider} -> {dest_path} ({size_mb:.2f} MB)")
            return True
        else:
            print(f"  [X] Corrupt or incomplete file detected for Scene {scene_num}. Removing.")
            if os.path.exists(dest_path):
                os.remove(dest_path)
            return False

    except Exception as err:
        print(f"  [X] Failed downloading Scene {scene_num}: {err}")
        if os.path.exists(dest_path):
            try:
                os.remove(dest_path)
            except OSError:
                pass
        return False


def download_pexels_asset(query, scene_num, media_type="video"):
    """Search & download from Pexels with browser headers and fallback."""
    if not PEXELS_API_KEY or PEXELS_API_KEY.startswith("YOUR_"):
        return False
        
    headers = {"Authorization": PEXELS_API_KEY}
    
    if media_type == "video":
        url = "https://api.pexels.com/videos/search"
        params = {"query": query, "per_page": 5, "orientation": "landscape"}
        res = robust_get_request(url, headers=headers, params=params, service_name="Pexels Video")
        if res and res.status_code == 200:
            data = res.json()
            videos = data.get("videos", [])
            for v in videos:
                video_files = v.get("video_files", [])
                if video_files:
                    # Sort by resolution, favoring 1080p for broad compatibility
                    sorted_files = sorted(video_files, key=lambda x: (x.get("width") or 0), reverse=True)
                    # Pick 1080p or highest available
                    target_file = next((f for f in sorted_files if f.get("width") == 1920), sorted_files[0])
                    download_url = target_file.get("link")
                    dest_file = os.path.join(OUTPUT_DIR, f"scene_{scene_num:02d}_pexels.mp4")
                    if download_file_stream(download_url, dest_file, scene_num, "Pexels"):
                        return True
    else:
        url = "https://api.pexels.com/v1/search"
        params = {"query": query, "per_page": 3, "orientation": "landscape"}
        res = robust_get_request(url, headers=headers, params=params, service_name="Pexels Photo")
        if res and res.status_code == 200:
            data = res.json()
            photos = data.get("photos", [])
            if photos:
                download_url = photos[0]["src"].get("original") or photos[0]["src"].get("large2x")
                dest_file = os.path.join(OUTPUT_DIR, f"scene_{scene_num:02d}_pexels.jpg")
                return download_file_stream(download_url, dest_file, scene_num, "Pexels")
                
    return False


def download_pixabay_asset(query, scene_num, media_type="video"):
    """Search & download from Pixabay with browser headers and fallback."""
    if not PIXABAY_API_KEY or PIXABAY_API_KEY.startswith("YOUR_"):
        return False

    if media_type == "video":
        url = "https://pixabay.com/api/videos/"
        params = {"key": PIXABAY_API_KEY, "q": query, "per_page": 5}
        res = robust_get_request(url, params=params, service_name="Pixabay Video")
        if res and res.status_code == 200:
            data = res.json()
            hits = data.get("hits", [])
            for hit in hits:
                videos_dict = hit.get("videos", {})
                # Medium or Large 1080p/4k video
                chosen = videos_dict.get("large") or videos_dict.get("medium") or videos_dict.get("small")
                if chosen and chosen.get("url"):
                    dest_file = os.path.join(OUTPUT_DIR, f"scene_{scene_num:02d}_pixabay.mp4")
                    if download_file_stream(chosen["url"], dest_file, scene_num, "Pixabay"):
                        return True
    else:
        url = "https://pixabay.com/api/"
        params = {"key": PIXABAY_API_KEY, "q": query, "image_type": "photo", "per_page": 3}
        res = robust_get_request(url, params=params, service_name="Pixabay Photo")
        if res and res.status_code == 200:
            data = res.json()
            hits = data.get("hits", [])
            if hits:
                download_url = hits[0].get("largeImageURL") or hits[0].get("webformatURL")
                dest_file = os.path.join(OUTPUT_DIR, f"scene_{scene_num:02d}_pixabay.jpg")
                return download_file_stream(download_url, dest_file, scene_num, "Pixabay")

    return False


def fetch_pixabay_audio(query):
    """
    Search for audio tracks on Pixabay Audio API.
    Returns list of audio items with title, duration, and direct download_url.
    """
    if not PIXABAY_API_KEY or PIXABAY_API_KEY.startswith("YOUR_"):
        return []

    # Dedicated Pixabay Audio API endpoint
    url = f"https://pixabay.com/api/audio/?key={PIXABAY_API_KEY}&q={query}&per_page=5"
    
    headers = {"User-Agent": BROWSER_USER_AGENT, "Accept": "*/*"}

    try:
        if USE_REQUESTS:
            response = requests.get(url, headers=headers, timeout=25)
            if response.status_code == 200:
                data = response.json()
                audio_list = []
                for hit in data.get("hits", []):
                    audio_list.append({
                        "title": hit.get("tags") or hit.get("name") or "Pixabay Track",
                        "duration": hit.get("duration"),
                        "download_url": hit.get("audio") or hit.get("download_url")  # Direct link to preview/download MP3
                    })
                return audio_list
        else:
            req = urllib.request.Request(url, headers=headers)
            with urllib.request.urlopen(req, timeout=25) as resp:
                if resp.status == 200:
                    data = json.loads(resp.read().decode('utf-8'))
                    audio_list = []
                    for hit in data.get("hits", []):
                        audio_list.append({
                            "title": hit.get("tags") or hit.get("name") or "Pixabay Track",
                            "duration": hit.get("duration"),
                            "download_url": hit.get("audio") or hit.get("download_url")
                        })
                    return audio_list
    except Exception as e:
        print(f"  [!] Pixabay Audio API notice: {e}")
    return []


def download_audio_track(download_url, dest_path, track_name):
    """Downloads an MP3 audio file with browser headers."""
    req_headers = {
        "User-Agent": BROWSER_USER_AGENT,
        "Accept": "audio/*, */*",
        "Referer": "https://pixabay.com/",
    }
    try:
        if USE_REQUESTS:
            with requests.get(download_url, headers=req_headers, stream=True, timeout=30) as r:
                if r.status_code == 200:
                    with open(dest_path, 'wb') as f:
                        for chunk in r.iter_content(chunk_size=65536):
                            if chunk:
                                f.write(chunk)
                    return True
        else:
            req = urllib.request.Request(download_url, headers=req_headers)
            with urllib.request.urlopen(req, timeout=30) as resp:
                if resp.status == 200:
                    with open(dest_path, 'wb') as f:
                        while True:
                            chunk = resp.read(65536)
                            if not chunk:
                                break
                            f.write(chunk)
                    return True
    except Exception as err:
        print(f"  [X] Failed downloading audio '{track_name}': {err}")
    return False


def process_gemma_plan(json_file_path="script_plan.json"):
    """Reads the JSON plan generated in AI Studio and downloads all scenes & audio assets."""
    if not os.path.exists(json_file_path):
        print(f"Error: '{json_file_path}' not found.")
        print("Please export or copy the JSON plan from the AI B-Roll Assistant and save it as 'script_plan.json'.")
        sys.exit(1)

    with open(json_file_path, "r", encoding="utf-8") as f:
        plan = json.load(f)

    project_name = plan.get("project_name", "video_project")
    scenes = plan.get("scenes", [])
    audio_suggestions = plan.get("audio_suggestions", {})
    total_scenes = len(scenes)

    print("=" * 65)
    print(f"🎬 Starting B-Roll & Audio Downloader: '{project_name}'")
    print(f"📁 Video Assets Dir: {os.path.abspath(OUTPUT_DIR)}")
    print(f"🎞️  Total Scenes: {total_scenes}")
    print("=" * 65)

    downloaded_count = 0

    # 1. Download Video Scenes
    for scene in scenes:
        scene_num = scene.get("scene_number", 1)
        script_line = scene.get("script_line", "")
        keywords = scene.get("search_keywords", "")
        media_type = scene.get("media_type", "video").lower()

        print(f"\\nScene {scene_num}/{total_scenes}:")
        print(f"  Script: \\"{script_line}\\"")
        print(f"  Keywords: \\"{keywords}\\" ({media_type})")

        # Fallback Strategy: Pexels first, then Pixabay
        success = download_pexels_asset(keywords, scene_num, media_type)
        if not success:
            print(f"  [~] Pexels missed or blocked. Trying Pixabay...")
            success = download_pixabay_asset(keywords, scene_num, media_type)

        if success:
            downloaded_count += 1
        else:
            print(f"  [X] Warning: Could not download suitable {media_type} for Scene {scene_num}.")

        # Polite delay between scene requests to respect rate limits
        time.sleep(0.8)

    # 2. Download Recommended Audio (Music & SFX)
    music_dir = os.path.join(OUTPUT_DIR, "audio", "music")
    sfx_dir = os.path.join(OUTPUT_DIR, "audio", "sfx")
    os.makedirs(music_dir, exist_ok=True)
    os.makedirs(sfx_dir, exist_ok=True)

    music_keywords = audio_suggestions.get("music_keywords", [])
    sfx_keywords = audio_suggestions.get("sfx_keywords", [])

    if music_keywords or sfx_keywords:
        print("\\n" + "=" * 65)
        print("🎵 Fetching Recommended Audio via Pixabay Audio API...")
        print("=" * 65)

        # Fetch Background Music
        for idx, kw in enumerate(music_keywords, 1):
            print(f"\\nSearching Music: \\"{kw}\\"...")
            tracks = fetch_pixabay_audio(kw)
            if tracks:
                top_track = tracks[0]
                dest_file = os.path.join(music_dir, f"music_{idx:02d}_{kw.replace(' ', '_')}.mp3")
                print(f"  -> Found: \\"{top_track['title']}\\" | Duration: {top_track.get('duration', 'N/A')}s")
                if top_track.get("download_url"):
                    if download_audio_track(top_track["download_url"], dest_file, top_track['title']):
                        print(f"  [✓] Saved music -> {dest_file}")
            else:
                print(f"  [i] Note: Pixabay Audio returned 0 tracks (or requires approved Audio key).")

            time.sleep(0.5)

        # Fetch SFX
        for idx, kw in enumerate(sfx_keywords, 1):
            print(f"\\nSearching SFX: \\"{kw}\\"...")
            tracks = fetch_pixabay_audio(kw)
            if tracks:
                top_track = tracks[0]
                dest_file = os.path.join(sfx_dir, f"sfx_{idx:02d}_{kw.replace(' ', '_')}.mp3")
                print(f"  -> Found SFX: \\"{top_track['title']}\\"")
                if top_track.get("download_url"):
                    if download_audio_track(top_track["download_url"], dest_file, top_track['title']):
                        print(f"  [✓] Saved SFX -> {dest_file}")
            time.sleep(0.5)

    print("\\n" + "=" * 65)
    print(f"✨ Finished! Successfully prepared {downloaded_count}/{total_scenes} video assets.")
    print(f"To import into Kdenlive:")
    print(f"  1. Open Kdenlive")
    print(f"  2. Project -> Add Clip or Folder -> Select '{os.path.abspath(OUTPUT_DIR)}'")
    print(f"  3. Drag video clips onto Video Track (V1) & audio into Audio Track (A1/A2)!")
    print("=" * 65)


if __name__ == "__main__":
    plan_path = sys.argv[1] if len(sys.argv) > 1 else "script_plan.json"
    process_gemma_plan(plan_path)
`;
}
